CREATE DATABASE SAMPLEUNIV;
CREATE SCHEMA "SAMPLEUNIV"."UNIVERSITY";
CREATE TABLE "UNIVERSITY"."STUDENT"
(STUDENT_ID CHAR(10) NOT NULL,
STUDENT_FIRSTNAME CHAR(20) NOT NULL,
STUDENT_LASTNAME CHAR(20) NOT NULL,
STUDENT_ADDRESS CHAR(100) NOT NULL,
STUDENT_PHONE CHAR(10) NOT NULL,
DEPARTMENT_ID INTEGER NOT NULL
);
CREATE TABLE "UNIVERSITY"."DEPARTMENT"
( DEPARTMENT_ID INTEGER NOT NULL,
DEPARTMENT_NAME CHAR(20) NOT NULL,
DEPARTMENT_ESTDATE DATE
);
ALTER TABLE "UNIVERSITY"."STUDENT" ADD CONSTRAINT
"STUDENT_PK" PRIMARY KEY(STUDENT_ID);
ALTER TABLE "UNIVERSITY"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY 
KEY(DEPARTMENT_ID);
ALTER TABLE "UNIVERSITY"."STUDENT" ADD CONSTRAINT "STUDENT_DEPARTMENT_FK" 
FOREIGN KEY(DEPARTMENT_ID) REFERENCES 
"UNIVERSITY"."DEPARTMENT"(DEPARTMENT_ID);