CREATE DATABASE CURSO;
CREATE SCHEMA "CURSO"."FCORDO";

CREATE TABLE fcordo. DIM_CLIENTES_OBJ_4 (
		CLIENTE_KEY VARCHAR2(50) NOT NULL,
		APELLIDO VARCHAR2(30),
		NOM VARCHAR2(50),
		DNI NUMBER,
		CUIL NUMBER,
		CUIT NUMBER,
		RAZON_SOCIAL VARCHAR2(10)
	)
;

CREATE TABLE fcordo.DIM_TIEMPO_OBJ_4 (
		FECHA DATE NOT NULL,
		ANIO NUMBER,
		PERIODO NUMBER,
		SEMANA_ANIO NUMBER
	)

CREATE TABLE fcordo.FACT_VENTAS_OBJ_4 (
		VENDEDOR_KEY VARCHAR2(60) NOT NULL,
		CLIENTE_KEY VARCHAR2(60) NOT NULL,
		FECHA DATE NOT NULL,
		MONTO_OPERACION NUMBER(30 , 4) NOT NULL
	)
;

CREATE TABLE fcordo.VENDEDORES_OBJ_4 (
		VENDEDOR_KEY VARCHAR2(60) NOT NULL,
		NOM VARCHAR2(50),
		APELLIDO VARCHAR2(10)
	)
;

CREATE INDEX fcordo.DIM_CLIENTES_OBJ_4_PK_IDX
	ON fcordo. DIM_CLIENTES_OBJ_4 (CLIENTE_KEY);

CREATE INDEX fcordo.DIM_TIEMPO_OBJ_4_PK_IDX
	ON fcordo.DIM_TIEMPO_OBJ_4 (FECHA);

CREATE INDEX fcordo.FACT_VENTAS_OBJ_4_PK_IDX
	ON fcordo.FACT_VENTAS_OBJ_4 (VENDEDOR_KEY,CLIENTE_KEY);

CREATE INDEX fcordo.VENDEDORES_OBJ_4_PK_IDX
	ON fcordo.VENDEDORES_OBJ_4 (VENDEDOR_KEY);

ALTER TABLE fcordo.DIM_CLIENTES_OBJ_4 ADD CONSTRAINT  DIM_CLIENTES_OBJ_4_PK PRIMARY KEY
	(CLIENTE_KEY) USING INDEX fcordo. DIM_CLIENTES_OBJ_4_PK_IDX;

ALTER TABLE fcordo.DIM_TIEMPO_OBJ_4 ADD CONSTRAINT  DIM_TIEMPO_OBJ_4_PK PRIMARY KEY
	(FECHA) USING INDEX fcordo. DIM_TIEMPO_OBJ_4_PK_IDX;

ALTER TABLE fcordo.FACT_VENTAS_OBJ_4 ADD CONSTRAINT FACT_VENTAS_OBJ_4_PK PRIMARY KEY
	(VENDEDOR_KEY,
	 CLIENTE_KEY) USING INDEX fcordo.FACT_VENTAS_OBJ_4_PK_IDX;

ALTER TABLE fcordo.VENDEDORES_OBJ_4 ADD CONSTRAINT VENDEDORES_OBJ_4_PK PRIMARY KEY
	(VENDEDOR_KEY) USING INDEX fcordo.VENDEDORES_OBJ_4_PK_IDX;

ALTER TABLE fcordo.FACT_VENTAS_OBJ_4 ADD CONSTRAINT FACT_VENTAS_OBJ_4_DIM_CLIENTES_OBJ_4_FK FOREIGN KEY
	(CLIENTE_KEY)
	REFERENCES fcordo.DIM_CLIENTES_OBJ_4
	(CLIENTE_KEY);

ALTER TABLE fcordo.FACT_VENTAS_OBJ_4 ADD CONSTRAINT FACT_VENTAS_OBJ_4_DIM_TIEMPO_OBJ_4_FK FOREIGN KEY
	(FECHA)
	REFERENCES fcordo.DIM_TIEMPO_OBJ_4
	(FECHA);


