--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "FCORDO"."DIM_COMPRADORES" (
		"ID_COMPRADOR" VARCHAR2(10) NOT NULL,
		"NOMBRE" VARCHAR2(40),
		"APELLIDO" VARCHAR2(40),
		"DNI" NUMBER NOT NULL,
		"RAZON_SOCIAL" VARCHAR2(40),
		"CUIT" NUMBER,
		"FECHA_ALTA" DATE,
		"FECHA_BAJA" DATE
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE TABLE "FCORDO"."FACT_VENTAS" (
		"FECHA" DATE,
		"ID_COMPRADOR" VARCHAR2(10) NOT NULL,
		"ID_VENDEDOR" NUMBER,
		"ID_ARTICULO" VARCHAR2(50),
		"PU" NUMBER(10 , 3),
		"CANTIDAD" NUMBER,
		"MONTO_TOTAL" NUMBER(10 , 3)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING
	NOCOMPRESS;

CREATE INDEX "FCORDO"."DIM_COMPRADORES_PK_IDX"
	ON "FCORDO"."DIM_COMPRADORES" ("ID_COMPRADOR");

CREATE INDEX "FCORDO"."FACT_VENTAS_PK_IDX"
	ON "FCORDO"."FACT_VENTAS" ("ID_COMPRADOR");

ALTER TABLE "FCORDO"."DIM_COMPRADORES" ADD CONSTRAINT "DIM_COMPRADORES_PK" PRIMARY KEY
	("ID_COMPRADOR") USING INDEX "FCORDO"."DIM_COMPRADORES_PK_IDX";

ALTER TABLE "FCORDO"."FACT_VENTAS" ADD CONSTRAINT "FACT_VENTAS_PK" PRIMARY KEY
	("ID_COMPRADOR") USING INDEX "FCORDO"."FACT_VENTAS_PK_IDX";

ALTER TABLE "FCORDO"."FACT_VENTAS" ADD CONSTRAINT "FACT_VENTAS_DIM_COMPRADORES_FK" FOREIGN KEY
	("ID_COMPRADOR")
	REFERENCES "FCORDO"."DIM_COMPRADORES"
	("ID_COMPRADOR");

COMMENT ON TABLE "FCORDO"."FACT_VENTAS" IS
'/*TABLA VENTAS*/';

